### ISSUE TITLE
微信小程序自定义按钮样式

### ISSUE THREAD

**Issue by youngjunning** [youngjunning/issues#19]
## 效果

![image](https://user-images.githubusercontent.com/13204332/39613225-62c78182-4f98-11e8-86a2-a834c62ac843.png)

## 全局定义

官方只提供了三个样式的按钮，这个根本就不够用的。经过一番探索，我发现了自定义按钮样式的方法：

```css
/*新增按钮类型*/
button[type="sishu"]{
  color:#ffffff;
  background-color: #0099d9
}
/*新增button-hover样式*/
button.sishu-button-hover{
  background-color: rgba(0, 153, 217,.7)
}
```

## 使用方法

type 属性指定你自定义的类型，hover-class 属性指定你自定义的 hover-class

```html
<button type="sishu" class="weui-btn" hover-class="sishu-button-hover" bindtap="saveCard">保存卡片分享朋友圈</button>
```
