### ISSUE TITLE
css 样式文字过长换行处理方法

### ISSUE THREAD

**Issue by youngjunning** [youngjunning/issues#215]
css强制换行、强制不换行及自动换行的写法

### css强制不换行

```css
div{white-space:nowrap;}
```

### css自动换行

```css
div{ word-wrap: break-word; word-break: normal; }
```

css强制英文单词断行

```css
div{word-break:break-all;}
```
