### ISSUE TITLE
微信小程序如何设置open-data的样式

### ISSUE THREAD

**Issue by youngjunning** [youngjunning/issues#32]
> open-data组件：https://developers.weixin.qq.com/miniprogram/dev/component/open-data.html

## 最佳实践

在 open-data 的类型中，只有 userAvatarUrl 是图片，但是微信可能为了兼容其他类型，默认是 `display:inline`，大家都知道行内元素是没有办法设置宽高的，我们只能把 open-data 设置为 `inline-block` 或 `block` 后才能设置它的宽高。

但是如果你还需要设置 userAvatar 为圆角，那么你还需要设置 `overflow:hidden`：

```css
open-data[type="userAvatarUrl"] {
  /* open-data 的 display 默认值是 inline ，需要改为 inline-block 或 block 才能控制宽高 */
  display: block;
  /* 设置 overflow 为 hidden 才能设置圆角 */
  overflow: hidden;
}
```

建议不要直接改变 open-data 的样式，而是像我一样只改变类型为 userAvatarUrl 的样式。做了如上样式重置，你就可以像使用 image 组件一样使用 open-data[type="userAvatarUrl"] 组件了

## 参考

![image](https://user-images.githubusercontent.com/13204332/39681603-dd815e06-51dd-11e8-9925-6229ef4edf06.png)
