### ISSUE TITLE
nth-child和nth-of-type应用案例

### ISSUE THREAD

**Issue by youngjunning** [youngjunning/issues#37]
## 区别

区别什么的张鑫旭在一篇文章中讲的很详细了：http://t.cn/R5XJUdX ，我就不赘述了，这篇文章主要是讲讲它们的应用案例

### 1、单个选择

```html
<ul>
  <li>1</li>
  <li>2（会变红）</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
</ul>
<div>
  <h1>标题1</h1>
  <h2>标题2（会变红）</h2>
  <h1>标题1</h1>
  <h2>标题2</h2>
  <h1>标题1</h1>
</div>
```

```css
div h2:nth-child(2){
  color:red
}
ul li:nth-of-type(2){
  color:red
}
```

### 1、奇偶选择

```html
<ul>
  <li>1（会变红）</li>
  <li>2（会变黄）</li>
  <li>3（会变红）</li>
  <li>4（会变黄）</li>
  <li>5（会变红）</li>
</ul>
```

```css
li:nth-child(odd){
  color:red
}
li:nth-child(even){
  color:yellow
}
/*等同于下面的代码*/
li:nth-of-type(odd){
  color:red
}
li:nth-of-type(even){
  color:yellow
}
```

### 2、区间选择

```html
<ul>
  <li>1（会变红）</li>
  <li>2（会变红）</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
</ul>
```

```css
li:nth-of-type(n+1){
  color:red
}
li:nth-of-type(n+3){
  color:black
}
```
