### ISSUE TITLE
微信小程序canvas实现实时圆形进度条

### ISSUE THREAD

**Issue by youngjunning** [youngjunning/issues#58]
## 前言

最近研究了下小程序的实时圆形进度条实现，下面这篇文章就来给大家详细的介绍了实现的方法示例，废话不多说，先来看看效果图吧

**点击中间按钮开始绘制**

![image](https://user-images.githubusercontent.com/13204332/40462384-455121f8-5f42-11e8-8521-1a32534ba1ed.png)

**绘制过程**

![image](https://user-images.githubusercontent.com/13204332/40462408-72fbb2e4-5f42-11e8-9097-38e92db1656a.png)

**绘制结束**

![image](https://user-images.githubusercontent.com/13204332/40462420-7e8e495a-5f42-11e8-97ea-6fa7d0cfb591.png)

## 实现思路

建立两个canvas标签，先绘制底层的浅灰色圆圈背景，再绘制上层的红色进度条。

## WXML代码

```html
<view class="wrap">
 <view class="circle-box">
 <canvas class="circle" style="width:200px; height:200px;" canvas-id="canvasArcCir">
 </canvas>
 <canvas class="circle" style="z-index: -5; width:200px; height:200px;" canvas-id="canvasCircle">
 </canvas>
 <view class="draw_btn" bindtap="drawCircle">开始动态绘制</view>
 </view>
</view>
```

## WXSS代码

> 特别注意：底层的canvas最好使用 `z-index:-5；`放置于底层

```css
page {
 width: 100%;
 height: 100%;
 background-color: #fff;
}

.circle-box {
 text-align: center;
 margin-top: 10vw;
}

.circle {
 position: absolute;
 left: 0;
 right: 0;
 margin: auto;
}

.draw_btn {
 width: 35vw;
 position: absolute;
 top: 33vw;
 right: 0;
 left: 0;
 margin: auto;
 border: 1px #000 solid;
 border-radius: 5vw;
}
```

## JS代码

```js
//获取应用实例
var app = getApp()

var interval;
var varName;
var ctx = wx.createCanvasContext('canvasArcCir');

Page({
 data: {
 },
 drawCircle: function () {
 clearInterval(varName);
 function drawArc(s, e) {
 ctx.setFillStyle('white');
 ctx.clearRect(0, 0, 200, 200);
 ctx.draw();
 var x = 100, y = 100, radius = 96;
 ctx.setLineWidth(5);
 ctx.setStrokeStyle('#d81e06');
 ctx.setLineCap('round');
 ctx.beginPath();
 ctx.arc(x, y, radius, s, e, false);
 ctx.stroke()
 ctx.draw()
 }
 var step = 1, startAngle = 1.5 * Math.PI, endAngle = 0;
 var animation_interval = 1000, n = 60;
 var animation = function () {
 if (step <= n) {
 endAngle = step * 2 * Math.PI / n + 1.5 * Math.PI;
 drawArc(startAngle, endAngle);
 step++;
 } else {
 clearInterval(varName);
 }
 };
 varName = setInterval(animation, animation_interval);
 },
 onReady: function () {
 //创建并返回绘图上下文context对象。
 var cxt_arc = wx.createCanvasContext('canvasCircle');
 cxt_arc.setLineWidth(6);
 cxt_arc.setStrokeStyle('#eaeaea');
 cxt_arc.setLineCap('round');
 cxt_arc.beginPath();
 cxt_arc.arc(100, 100, 96, 0, 2 * Math.PI, false);
 cxt_arc.stroke();
 cxt_arc.draw();
 }
})
```

## 后记

1. 关于小程序canvas绘制，请观看微信小程序官方文档绘制
2. 开始绘制的路径可以根据 JS代码中的变量startAngle 来选择从哪里开始绘制
