### ISSUE TITLE
微信小程序scroll-view横向滚动

### ISSUE THREAD

**Issue by youngjunning** [youngjunning/issues#9]
### 注意事项

1.设置滚动项 `display：inline-block;` 
2.设置滚动视图容器 `white-space: nowrap;` 
3.滚动项不要用float

### 代码

```css
#model {
  height: 900rpx;
  white-space: nowrap;
}

#model .modelList {
  display: inline-block;
  width: 600rpx;
  height: 900rpx;
  margin-right: 15px;
}

#model .modelList:first-child {
  margin-left: 24px
}
```

```html
<scroll-view scroll-x="true" id="model">
  <view class="modelList" style="background:#0099d9"
    wx:for="{{templates}}"
    wx:key="objectId"
    data-index="{{index}}"
    data-imgurl="{{item.imgUrl}}"
    bindtap="selectTemplate">
      <image src="{{item.imgUrl}}" style="height:100%"></image>
    </view>
</scroll-view>
```

## 方案二

这个方案的问题在于，你没办法控制项的宽度。应用场景比较窄

```html
<scroll-view scroll-x="true" id="yourId">
  <!--scroll-view 采用 flex是不起作用的，建议在 scroll-view里再套一层view，对这个view采用flex-->
  <view class="weui-flex">
  <!--wxss 设置子元素 flex: 1 0 50%;height: ...rpx-->
    <view style="background:green"></view>
      <view style="background:red"></view>
      <view style="background: yellow;"></view>
      <view style="background: blue;"></view>
  </view>
</scroll-view>
```
